
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class JobRequirementDetailsTable
{

    public int JobRequirementDetailsID { get; set; }

    public int JobRequirementID { get; set; }

    public string JobRequirementDetails { get; set; }

    public Nullable<int> PostJobID { get; set; }



    public virtual JobRequirementsTable JobRequirementsTable { get; set; }

    public virtual PostJobTable PostJobTable { get; set; }

}

}
